# Generated by Django 5.2.15 on 2026-08-09 04:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protocols', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('3_MONTHS', 'Every 3 months'), ('6_MONTHS', 'Every 6 months')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('last_completed_at', models.DateTimeField(blank=True, null=True)),
                ('protocol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_plan', to='protocols.protocol')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_plans', to='tenants.tenant')),
            ],
            options={
                'db_table': 'monitoring_plans',
                'ordering': ['next_due_date'],
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('incident_type', models.CharField(choices=[('PARTICIPANT_SAFETY', 'Human rights or participant safety concern'), ('UNAPPROVED_PROTOCOL_CHANGE', 'Unapproved research purpose or methodology change'), ('SERIOUS_UNEXPECTED_EVENT', 'Serious unexpected event')], max_length=40)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('ACTION_REQUIRED', 'Action required'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='SUBMITTED', max_length=20)),
                ('occurred_at', models.DateTimeField()),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='protocols.protocol')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_incident_reports', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='tenants.tenant')),
                ('monitoring_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='monitoring.monitoringplan')),
            ],
            options={
                'db_table': 'incident_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('report_type', models.CharField(choices=[('PERIODIC', 'Periodic'), ('FINAL', 'Final')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('ACCEPTED', 'Accepted'), ('ADDITIONAL_INFORMATION_REQUIRED', 'Additional information required')], default='DRAFT', max_length=40)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('issues', models.TextField(blank=True)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('monitoring_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='monitoring.monitoringplan')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='protocols.protocol')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_progress_reports', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_progress_reports', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='tenants.tenant')),
            ],
            options={
                'db_table': 'progress_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
