# Generated by Django 5.2.15 on 2026-08-12 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='is_deleted',
        ),
    ]
