# Generated by Django 5.2.15 on 2026-08-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_remove_auditlog_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-occurred_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='auditlog',
            name='event_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='occurred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
