# Generated by Django 5.2.15 on 2026-06-29 11:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protocols', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('decision_type', models.CharField(choices=[('approved', 'Approved'), ('conditional_approval', 'Conditional Approval'), ('revision_required', 'Revision Required'), ('rejected', 'Rejected')], max_length=30)),
                ('quorum_met', models.BooleanField()),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions_made', to=settings.AUTH_USER_MODEL)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='protocols.protocol')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'decisions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='decision.decision')),
            ],
            options={
                'db_table': 'decision_conditions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='decision.decision')),
            ],
            options={
                'db_table': 'decision_letters',
                'ordering': ['-created_at'],
            },
        ),
    ]
