# Generated by Django 5.2.15 on 2026-06-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_id', models.UUIDField()),
                ('reviewer_id', models.UUIDField()),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('OVERDUE', 'Overdue')], default='ASSIGNED', max_length=30)),
                ('recommendation', models.CharField(blank=True, choices=[('APPROVE', 'Approve'), ('APPROVE_WITH_CHANGES', 'Approve With Changes'), ('DEFER', 'Defer'), ('REJECT', 'Reject')], max_length=50, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('comments', models.TextField(blank=True, default='')),
                ('due_date', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='ReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_id', models.UUIDField()),
                ('reviewer_id', models.UUIDField()),
                ('role', models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary')], default='PRIMARY', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'review_assignments',
            },
        ),
    ]
