# Generated by Django 5.2.15 on 2026-09-15 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0001_initial'),
        ('reviews', '0004_review_require_tenant_protocol_reviewer'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewassignment',
            name='protocol_id',
        ),
        migrations.RemoveField(
            model_name='reviewassignment',
            name='reviewer_id',
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='protocol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_assignments', to='protocols.protocol'),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_assignments', to='tenants.tenant'),
        ),
    ]
