# Generated by Django 5.2.15 on 2026-09-15 01:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('incomplete', 'Incomplete'), ('complete', 'Complete'), ('closed', 'Closed')], default='received', max_length=30)),
                ('incomplete_reason', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='protocols.protocol')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocol_submissions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocol_submissions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'protocol_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
