# Generated by Django 5.2.15 on 2026-09-15 02:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0002_protocolsubmission'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('research_introduction', 'Research Introduction'), ('methodology', 'Methodology'), ('risk_assessment', 'Risk Assessment'), ('informed_consent', 'Informed Consent'), ('questionnaire', 'Questionnaire'), ('data_protection_plan', 'Data Protection Plan'), ('ai_cyber_assessment', 'AI/Cyber Assessment'), ('pi_signature', 'PI Signature'), ('other', 'Other')], max_length=50)),
                ('file_reference', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='protocols.protocolsubmission')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_documents', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_submission_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submission_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
