# Generated by Django 5.2.15 on 2026-09-15 07:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0003_submissiondocument'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreliminaryCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField()),
                ('result', models.CharField(choices=[('received', 'Received'), ('incomplete', 'Incomplete'), ('complete', 'Complete'), ('closed', 'Closed')], max_length=30)),
                ('missing_document_types', models.JSONField(blank=True, default=list)),
                ('correction_due_at', models.DateTimeField(blank=True, null=True)),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preliminary_checks', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preliminary_checks', to='protocols.protocolsubmission')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preliminary_checks', to='tenants.tenant')),
            ],
            options={
                'db_table': 'preliminary_checks',
                'ordering': ['-checked_at'],
            },
        ),
    ]
