# Generated by Django 5.2.15 on 2026-09-15 12:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0005_alter_preliminarycheck_result'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('classification', models.CharField(choices=[('exempt', 'Exempt'), ('simplified', 'Simplified'), ('full', 'Full Review')], max_length=20)),
                ('evaluated_at', models.DateTimeField()),
                ('rationale', models.TextField()),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classification_assessments', to=settings.AUTH_USER_MODEL)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classification_assessments', to='protocols.protocol')),
                ('protocol_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classification_assessments', to='protocols.protocolversion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classification_assessments', to='tenants.tenant')),
            ],
            options={
                'db_table': 'classification_assessments',
                'ordering': ['-evaluated_at'],
            },
        ),
    ]
