# Generated by Django 5.2.15 on 2026-09-19 08:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protocols', '0006_classificationassessment'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictOfInterestDeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('conflict_types', models.JSONField(blank=True, default=list)),
                ('description', models.TextField()),
                ('declared_at', models.DateTimeField()),
                ('signature_reference', models.CharField(blank=True, max_length=500)),
                ('declarant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conflict_of_interest_declarations', to=settings.AUTH_USER_MODEL)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conflict_of_interest_declarations', to='protocols.protocol')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conflict_of_interest_declarations', to='tenants.tenant')),
            ],
            options={
                'db_table': 'conflict_of_interest_declarations',
                'ordering': ['-declared_at'],
            },
        ),
    ]
