# Generated by Django 5.2.15 on 2026-09-22 00:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        ('meetings', '0004_meetingvote'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictOfInterestRecusal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('recused_at', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conflict_of_interest_recusals', to='meetings.meetingagenda')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recusals', to='compliance.conflictofinterestdeclaration')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conflict_of_interest_recusals', to='meetings.meetingparticipant')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conflict_of_interest_recusals', to='tenants.tenant')),
            ],
            options={
                'db_table': 'conflict_of_interest_recusals',
                'ordering': ['-recused_at'],
                'constraints': [models.UniqueConstraint(fields=('declaration', 'agenda', 'participant'), name='unique_conflict_of_interest_recusal')],
            },
        ),
    ]
