# Generated by Django 5.2.15 on 2026-09-24 11:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_conflictofinterestrecusal'),
        ('meetings', '0005_meetingminutes'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingMinutesRecusal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('minutes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recusals', to='meetings.meetingminutes')),
                ('recusal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='minutes_record', to='compliance.conflictofinterestrecusal')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meeting_minutes_recusals', to='tenants.tenant')),
            ],
            options={
                'db_table': 'meeting_minutes_recusals',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
