# Generated by Django 5.2.15 on 2026-09-27 11:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_meetingminutesrecusal'),
        ('protocols', '0006_classificationassessment'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EthicsViolation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('violation_type', models.CharField(choices=[('UNAUTHORIZED_RESEARCH', 'Starting research without approval'), ('DATA_FALSIFICATION', 'Falsifying data'), ('PARTICIPANT_RIGHTS_VIOLATION', 'Violating participant rights'), ('CONFIDENTIALITY_BREACH', 'Breaching confidentiality'), ('PROGRESS_REPORT_NOT_SUBMITTED', 'Failing to submit progress reports')], max_length=50)),
                ('description', models.TextField()),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ethics_violations', to='protocols.protocol')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ethics_violations', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ethics_violations',
                'ordering': ['-created_at'],
            },
        ),
    ]
