# Generated by Django 5.2.15 on 2026-08-02 03:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('chair', 'Chair'), ('reviewer', 'Reviewer'), ('secretary', 'Secretary'), ('guest', 'Guest')], default='reviewer', max_length=20)),
                ('attendance_status', models.CharField(choices=[('invited', 'Invited'), ('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excused')], default='invited', max_length=20)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meeting_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['meeting', 'user'],
                'constraints': [models.UniqueConstraint(fields=('meeting', 'user'), name='unique_meeting_participant')],
            },
        ),
    ]
