# Generated by Django 5.2.15 on 2026-08-02 12:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meetingagenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('vote', models.CharField(choices=[('approve', 'Approve'), ('approve_with_changes', 'Approve with Changes'), ('revisions_required', 'Revisions Required'), ('reject', 'Reject'), ('abstain', 'Abstain')], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='meetings.meetingagenda')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='meetings.meetingparticipant')),
            ],
            options={
                'ordering': ['agenda', 'participant'],
                'constraints': [models.UniqueConstraint(fields=('agenda', 'participant'), name='unique_vote_per_participant')],
            },
        ),
    ]
